target_ns: paa
cluster_name: paa
bundle_id: "cis-b.5.1.1-gen"
bundle_title: "CIS Benchmark for K8S 5.1.1 (Kyverno)"
work_dir: "{{ lookup('env', 'WORK_DIR') | default('/tmp/caa-bench', true) }}"

bundle_input_file: "{{ lookup('env', 'BUNDLE_INPUT_FILE') | default('../input.json', true) }}"
bundle_input: "{{ lookup('file', bundle_input_file) | from_json }}"

provided_kubeconfig: "{{ bundle_input.kubeconfig | default('') }}"
kubeconfig: "{{ work_dir }}/kubeconfig.caa.yaml"
path_to_status: "{{ work_dir }}/status.json"

shared_workspace: "{{ bundle_input.shared_workspace }}"
agent_kubeconfig: "{{ shared_workspace }}/kubeconfig.yaml"
agent_output: "{{ shared_workspace }}/agent_output.data"
agent_output_destination: "{{ work_dir }}/agent_output"