---
- import_tasks: install_astronomy_shop.yaml
- import_tasks: uninstall_astronomy_shop.yaml
- import_tasks: install_deathstarbench_hotel_reservations.yaml
- import_tasks: uninstall_deathstarbench_hotel_reservations.yaml
- import_tasks: uninstall_sample_applications.yaml
- import_tasks: register_deployment_time.yaml
