---
- name: Get the assertion.json from S3
  amazon.aws.s3_object:
    endpoint_url: "https://s3.us-east-2.amazonaws.com"
    bucket: "{{ s3_bucket_name_for_results }}"
    object: "/{{ sre_agent_name__version_number }}/{{run_uuid}}/{{scenario_number}}/{{run_number}}/assertion.json"
    dest: "/tmp/assertion.json"
    mode: get
  tags:
    - book_keeping
  when:
    - sre_bench_runner
    - run_uuid is defined and scenario_number is defined and run_number is defined

- name: Read deployment and fault injection details from assertion json
  set_fact:
    assertion_array: "{{ lookup('file', assertion_filepath ) | from_json | json_query('status.conditions') }}"
  tags:
    - uninstall_sample_applications
  when: 
    - sre_bench_runner

- name: Update assertion array content
  set_fact:
    updated_assertion_array: "{{ assertion_array + [{'type': 'Destroyed', 'status': namespaces.resources | json_query('[].metadata.name') | list | intersect(namespace_delete_list) | length < 1, 'lastTransitionTime':now(utc=True, fmt='%Y-%m-%dT%H:%M:%SZ')}] }}"
  tags:
    - uninstall_sample_applications
  when: 
    - sre_bench_runner

- name: Create json structure for assertion json file
  set_fact:
    assertion_json:
      status:
        conditions: "{{ updated_assertion_array }}"
  tags:
    - uninstall_sample_applications
  when: 
    - sre_bench_runner

- name: Update assertion json file
  copy:
    content: "{{ assertion_json | to_json | indent(2) }}"
    dest: "{{ assertion_filepath }}"
    mode: "0644"
  tags:
    - uninstall_sample_applications
  when: 
    - sre_bench_runner

- name: Upload the assertion JSON to S3
  amazon.aws.s3_object:
    endpoint_url: "https://s3.us-east-2.amazonaws.com"
    bucket: "{{ s3_bucket_name_for_results }}"
    object: "/{{ sre_agent_name__version_number }}/{{run_uuid}}/{{scenario_number}}/{{run_number}}/assertion.json"
    src: "/tmp/assertion.json"
    mode: put
  tags:
    - uninstall_sample_applications
  when:
    - sre_bench_runner
    - run_uuid is defined and scenario_number is defined and run_number is defined
