---
scenario_domain: finops
sample_application: otel_astronomy_shop

is_install_chaos_mesh: false
target_namespace_name: "{{ otel_astronomy_app_namespace_project_name }}"
target_deployments:
  - "{{ otel_astronomy_app_installation_name }}-accountingservice"
  - "{{ otel_astronomy_app_installation_name }}-adservice"
  - "{{ otel_astronomy_app_installation_name }}-cartservice"
  - "{{ otel_astronomy_app_installation_name }}-checkoutservice"
  - "{{ otel_astronomy_app_installation_name }}-currencyservice"
  - "{{ otel_astronomy_app_installation_name }}-emailservice"
  - "{{ otel_astronomy_app_installation_name }}-flagd"
  - "{{ otel_astronomy_app_installation_name }}-frauddetectionservice"
  - "{{ otel_astronomy_app_installation_name }}-frontend"
  - "{{ otel_astronomy_app_installation_name }}-frontendproxy"
  - "{{ otel_astronomy_app_installation_name }}-imageprovider"
  - "{{ otel_astronomy_app_installation_name }}-kafka"
  - "{{ otel_astronomy_app_installation_name }}-otelcol"
  - "{{ otel_astronomy_app_installation_name }}-paymentservice"
  - "{{ otel_astronomy_app_installation_name }}-productcatalogservice"
  - "{{ otel_astronomy_app_installation_name }}-quoteservice"
  - "{{ otel_astronomy_app_installation_name }}-recommendationservice"
  - "{{ otel_astronomy_app_installation_name }}-shippingservice"
  - "{{ otel_astronomy_app_installation_name }}-valkey"

docs_incident_38:
  "id": 38
  "name": "Large cost variation"
  "platform": kubernetes
  "dsl_format": groups
  "description": "Services has scaled up despite low traffic"
  "application": "otel_astronomy_shop"
  "complexity": "Medium"
  "inject_fault_unused": true
  "agent_operation_timeout_sec": 3000
  "bundle_ready_timeout_sec": 3000

  fault:
    - "entity":
        "name": "otel-demo-*"
        "kind": "HorizontalPodAutoscaler"
        "group_id": "otel-demo-horizontal-pod-autoscalers"
      "condition": "Misconfigured HPA"
      "category": "Other"
      "fault_mechanism": "custom(other)"

  alerts: 
    - id: high_cost_variation
      text: "Cost has increased significantly despite having low utilization"
      group_id: otel-demo-namespace-1

  groups:
    - id: otel-demo-namespace-1
      kind: Namespace
      name: otel-demo
      namespace: ""
    - id: otel-demo-horizontal-pod-autoscalers
      kind: HorizontalPodAutoscaler
      namespace: otel-demo
      filter:
      - "*.*"
      root_cause: true

  recommended_actions:
  - solution:
      id: "investigate_detect_misconfigured_autoscaler"
      actions:
      - check current and recent past utilization numbers through promethous
      - found a temporary spike in application load
      - detect misconfiguration in auto-scaler for scaling down
    # - time_to_clear_alert: 120s

  metrics:
  - type: "rate"
    value: "27.8"
  - type: "efficiency"
    value: "52"
